name: rocketbot build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-arch-debug:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install packages
        run: pacman -S --needed --noconfirm cargo git python-toml
      - name: trust repo directory
        run: git config --global --add safe.directory /__w/rocketbot/rocketbot
      - name: check out repository code
        uses: actions/checkout@v3
      - name: run debug build
        run: cargo build --all-targets --verbose
      - name: run debug tests
        run: cargo test --verbose
      - name: upload debug binary
        uses: actions/upload-artifact@v3
        with:
          name: icingcake-debug
          path: |
            target/debug/icingcake
  build-arch-release:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install packages
        run: pacman -S --needed --noconfirm cargo git python-toml
      - name: trust repo directory
        run: git config --global --add safe.directory /__w/rocketbot/rocketbot
      - name: check out repository code
        uses: actions/checkout@v3
      - name: run release build
        run: cargo build --all-targets --release --verbose
      - name: run release tests
        run: cargo test --release --verbose
      - name: upload release binary
        uses: actions/upload-artifact@v3
        with:
          name: icingcake-release
          path: |
            target/release/icingcake
  build-ubuntu-focal-release:
    runs-on: ubuntu-latest
    container: ubuntu:focal
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/UTC
    steps:
      - name: update apt database
        run: apt-get -y update
      - name: update packages
        run: apt-get -y dist-upgrade
      - name: install packages
        run: apt-get -y install curl build-essential pkg-config python3 git libssl-dev
      - name: install rustup
        run: "curl --proto '=https' -sSf https://sh.rustup.rs | sh -s -- -y"
      - name: trust repo directory
        run: git config --global --add safe.directory /__w/rocketbot/rocketbot
      - name: check out repository code
        uses: actions/checkout@v3
      - name: run release build
        run: '. $HOME/.cargo/env && cargo build --all-targets --release --verbose'
      - name: run release tests
        run: '. $HOME/.cargo/env && cargo test --release --verbose'
      - name: upload release binary
        uses: actions/upload-artifact@v3
        with:
          name: icingcake-release-ubuntu-focal
          path: |
            target/release/icingcake
